<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>


    <PropertyGroup>
        <PackageId>KitCli.Abstractions</PackageId>
        <Version>1.2.0</Version>
        <Authors>Joshua Crowe</Authors>
        <Company>KitCli</Company>
    </PropertyGroup>


    <ItemGroup>
      <PackageReference Include="Spectre.Console" Version="0.57.2" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
    </ItemGroup>

</Project>
